#include "object_defs.hpp"

const char* effect_names[51] = {
    "PHYSIC IMMUNITY",
    "MAGIC IMMUNITY",
    "POISON IMMUNITY",
    "ACID IMMUNITY",
    "UNFROZENABLE",
    "UNFLAMED",
    "DIELECTRIC",

    "MAGIC ABSORBTION",
    "POISON ABSORBTION",
    "ACID ABSORBTION",
    "ICE ABSORBTION",
    "FIRE ABSORBTION",
    "ELECTRIC ABSORBTION",

    "PHYSIC PROTECT",
    "MAGIC PROTECT",
    "POISON PROTECT",
    "ACID PROTECT",
    "FROZING PROTECT",
    "FIRE PROTECT",
    "ELECTRIC PROTECT",

    "PHYSIC WEAKNESS",
    "MAGIC WEAKNESS",
    "POISON WEAKNESS",
    "ACID WEAKNESS",
    "FROZING WEAKNESS",
    "FIRE WEAKNESS",
    "ELECTRIC WEAKNESS",

    "FLYING",
    "CORROSION",
    "SHOCKED",
    "FIRING",
    "WET",
    "STUNNED",
    "FRIZED",
    "SPLITTED OPEN",
    "DEAD",
    "REGENERATION",
    "POISONED",
    "MANA REGENERATION",

    "ACID ATTACK",
    "CRUSH ATTACK",
    "SLASH ATTACK",
    "COLUSH ATTACK",
    "MAGIC ATTACK",

    "HEAL",
    "POISON DAMAGE",
    "MANA RESTORE",
    "FIRE DAMAGE",
    "ELECTRIC DAMAGE",
    "ICE DAMAGE"
};

const char* property_names[3] = {
    "HEALTH",
    "MANA",
    "STRENGTH"
};